# Generated by Django 2.1.5 on 2019-03-18 01:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Checklist',
            fields=[
                ('Checklist_id', models.IntegerField(primary_key=True, serialize=False)),
                ('Term_season', models.CharField(max_length=6)),
                ('Term_Year', models.IntegerField()),
                ('Recommendation_letters', models.BooleanField(default=False)),
                ('Transcript', models.BooleanField(default=False)),
                ('Tests', models.BooleanField(default=False)),
                ('Statement_of_purpose', models.BooleanField(default=False)),
                ('Personal_statement', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('Feedback_id', models.IntegerField(primary_key=True, serialize=False)),
                ('Feedback_status', models.CharField(choices=[('ACCEPTED', 'Accepted'), ('WAITLISTED', 'Waitlisted'), ('DENIED', 'Denied')], max_length=1)),
                ('GPA', models.IntegerField()),
                ('Standardized_Test', models.IntegerField()),
                ('Recommendation', models.CharField(max_length=1000)),
                ('Research', models.CharField(max_length=1000)),
                ('Checklist_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checklist.Checklist')),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('Program_id', models.IntegerField(primary_key=True, serialize=False)),
                ('Program_name', models.CharField(max_length=100)),
                ('College', models.CharField(max_length=100)),
                ('Degree', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Requirement',
            fields=[
                ('Requirement_id', models.IntegerField(primary_key=True, serialize=False)),
                ('Term_season', models.CharField(max_length=6)),
                ('Term_year', models.IntegerField()),
                ('Recommendation_letters', models.BooleanField(default=False)),
                ('Transcript', models.BooleanField(default=False)),
                ('Tests', models.BooleanField(default=False)),
                ('Statement_of_purpose', models.BooleanField(default=False)),
                ('Personal_statement', models.BooleanField(default=False)),
                ('Program_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checklist.Program')),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('School_id', models.IntegerField(primary_key=True, serialize=False)),
                ('School_desc', models.CharField(max_length=100)),
                ('School_name', models.CharField(max_length=100)),
                ('Address_street', models.CharField(max_length=100)),
                ('Address_city', models.CharField(max_length=100)),
                ('Address_state', models.CharField(max_length=100)),
                ('Address_zipcode', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('student_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('School_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checklist.School')),
            ],
            options={
                'abstract': False,
            },
            bases=('checklist.student',),
        ),
        migrations.AddField(
            model_name='program',
            name='School_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checklist.School'),
        ),
        migrations.AddField(
            model_name='checklist',
            name='Requirement_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checklist.Requirement'),
        ),
        migrations.AddField(
            model_name='checklist',
            name='Student_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
